import test from 'node:test';
import assert from 'node:assert/strict';
import {MusicDialogue,searchTracks} from '../dist/music-engine.js';
import {STARTER_TRACKS,filenameTags,readTags} from '../dist/music-library.js';

test('the original classical request builds a real three-recording queue',()=>{const d=new MusicDialogue();const r=d.request('Can you play something classical?',STARTER_TRACKS);assert.equal(r.type,'play');assert.equal(r.queue.length,3);assert.equal(r.track.artist,'Ludwig van Beethoven');assert.ok(r.queue.every(t=>t.url.startsWith('https://upload.wikimedia.org/')));});
test('artist search asks before playback, and a follow-up resolves the same match',()=>{const d=new MusicDialogue();const r=d.request('What do you have by Bach?',STARTER_TRACKS);assert.equal(r.type,'choices');assert.equal(r.tracks[0].id,'air');const next=d.request('play it',STARTER_TRACKS);assert.equal(next.type,'play');assert.equal(next.track.id,'air');assert.equal(d.pending,null);});
test('vague requests and ambiguous artist names require clarification',()=>{const d=new MusicDialogue();assert.equal(d.request('play music',STARTER_TRACKS).type,'choices');const choice=d.request('something upbeat',STARTER_TRACKS);assert.equal(choice.track.id,'maple-leaf');const tracks=[...STARTER_TRACKS,{...STARTER_TRACKS[0],id:'beethoven2',title:'Symphony No. 5'}];assert.equal(d.request('play Beethoven',tracks).type,'choices');assert.equal(d.request('the second one',tracks).track.id,'beethoven2');});
test('missing artists and negated requests never start substitute audio',()=>{const d=new MusicDialogue();assert.equal(d.request('Play Madonna',STARTER_TRACKS).type,'missing');assert.match(d.request('Play Madonna',STARTER_TRACKS).text,/couldn’t find/);assert.equal(d.request("Don't play classical music",STARTER_TRACKS).type,'reply');assert.equal(d.pending,null);assert.equal(d.request('Tell me a joke',STARTER_TRACKS),null);});
test('playback controls win over pending song selection',()=>{const d=new MusicDialogue();d.request('play music',STARTER_TRACKS);assert.equal(d.request('pause',STARTER_TRACKS).type,'pause');assert.equal(d.pending,null);assert.deepEqual(d.request('volume 150',STARTER_TRACKS),{type:'volume',value:1});assert.equal(d.request('next track',STARTER_TRACKS).type,'next');assert.equal(d.request('resume',STARTER_TRACKS).type,'resume');});
test('search supports title, performer, mood, and artist transliteration',()=>{assert.equal(searchTracks(STARTER_TRACKS,'Kevin MacLeod')[0].id,'canon');assert.equal(searchTracks(STARTER_TRACKS,'calm').length,3);assert.equal(searchTracks(STARTER_TRACKS,'Бетховен')[0].id,'moonlight');assert.equal(searchTracks(STARTER_TRACKS,'Maple Leaf Rag')[0].id,'maple-leaf');});
test('local filenames supply useful tags; malformed ID3 falls back safely',async()=>{assert.deepEqual(filenameTags('Madonna - Holiday.mp3'),{title:'Holiday',artist:'Madonna',genre:'Your music'});const file=new Blob(['not an ID3 header']);file.name='Test Artist - Test Song.wav';assert.equal((await readTags(file)).artist,'Test Artist');});

test('Russian music requests preserve Cyrillic letters and resolve genres',()=>{const d=new MusicDialogue();assert.equal(d.request('Включи классику',STARTER_TRACKS).queue.length,3);assert.equal(d.request('сыграй что-нибудь спокойное',STARTER_TRACKS).type,'play');assert.equal(d.request('Поставь Бетховена',STARTER_TRACKS).track.id,'moonlight');});
